### ISSUE TITLE
*** WARNING: Could not find audio clip "repeater" in context "EchoLink"

### ISSUE THREAD

**Issue by Dloranger** [OpenRepeater/orp-sounds#1]
workaround

`cp /usr/share/svxlink/sounds/en_US/Core/repeater.wav /usr/share/svxlink/sounds/en_US/EchoLink/`

**Comment by abcrawford** [comment]
This is more of an issue with the build script right now. I've added this fix to the build script where I am linking back to other core files (instead of copying). While this is a patch right now, it will allow me to collect a list of files that should be linked. Then when I get a chance to thoroughly test if GitHub will support relative symlinking, then I will move these links out of the script and into this repo.

So the script is effectively doing the following:
ln -s "/usr/share/svxlink/sounds/en_US/Core/repeater.wav" "/usr/share/svxlink/sounds/en_US/Default/repeater.wav"

You can use the same command on an older build if it is missing on your system. Future builds with the script this should be corrected.
